import type { NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { WorkTicketCard } from "~/features/worktickets/components/cards/WorkTicketCard";

const Screen: NextPage = () => {
  const workTicketsQuery = api.workTicket.all.useQuery();

  const deletePostMutation = api.post.delete.useMutation({
    onSettled: () => workTicketsQuery.refetch(),
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center ">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Work tickets
          </h1>

          {/* <CreatePostForm /> */}

          {workTicketsQuery.data ? (
            <div className="w-full max-w-2xl">
              {workTicketsQuery.data?.length === 0 ? (
                <span>There are no posts!</span>
              ) : (
                <div className="flex h-[40vh] justify-center overflow-y-scroll px-4 text-2xl">
                  <div className="flex w-full flex-col gap-4">
                    {workTicketsQuery.data?.map((p) => {
                      return <WorkTicketCard key={p.id} {...p} />;
                    })}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <p>Loading...</p>
          )}
        </div>
      </main>
    </>
  );
};

export default Screen;
