import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";

import { api } from "~/utils/api";
import { Button } from "~/features/shared/components/Button";
import { PageHeader } from "~/features/shared/components/PageHeader";
import { PageLayout } from "~/features/shared/components/PageLayout";
import { WorkTicketCard } from "~/features/worktickets/components/cards/WorkTicketCard";

const Screen: NextPage = () => {
  const workTicketsQuery = api.workTicket.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <PageHeader
          title="Work tickets"
          ActionComponents={
            <NextLink href={"work-tickets/create"}>
              <Button variant="outline">Create workticket</Button>
            </NextLink>
          }
        />

        {workTicketsQuery.data ? (
          <div className="w-full max-w-2xl">
            {workTicketsQuery.data?.length === 0 ? (
              <span>There are no posts!</span>
            ) : (
              <div className="flex h-[40vh] justify-center overflow-y-scroll px-4 text-2xl">
                <div className="flex w-full flex-col gap-4">
                  {workTicketsQuery.data?.map((p) => {
                    return <WorkTicketCard key={p.id} {...p} />;
                  })}
                </div>
              </div>
            )}
          </div>
        ) : (
          <p>Loading...</p>
        )}
      </PageLayout>
    </>
  );
};

export default Screen;
